import { TrackPreset } from './types';

export const TECHNO_PRESETS: TrackPreset[] = [
  {
    id: 'peak-time-techno',
    name: 'Peak Time Energy',
    genre: 'Peak Time Techno',
    bpm: 132,
    key: 'C Minor (Acid)',
    description: 'Driving peak-time weapon with a powerful, round low-end kick, relentless offbeat hats, and a sharp rhythmic synthesizer sequence.',
    patterns: {
      kick:  [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      hat:   [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true],
      clap:  [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      synth: [true, false, true, true, false, true, false, true, true, false, true, false, true, true, false, false],
    },
    synthNotes: [0, 2, 3, 4, 1, 3, 2, 4, 3, 1, 5, 2, 4, 3, 0, 0],
    cutoff: 950,
    resonance: 8,
    delayTime: 0.25,
    decay: 0.16,
  },
  {
    id: 'goa',
    name: 'Goa Sunrise',
    genre: 'Goa Trance',
    bpm: 140,
    key: 'F# Phrygian',
    description: 'Nostalgic 140 BPM acid-infused Goa trance. Features organic melodic scales, resonant synth sweeps, and high-frequency driving tribal energy.',
    patterns: {
      kick:  [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      hat:   [false, false, true, false, false, false, true, false, false, false, true, false, true, true, true, false],
      clap:  [false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false],
      synth: [false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true],
    },
    synthNotes: [0, 1, 2, 3, 0, 3, 2, 1, 0, 2, 4, 5, 0, 5, 4, 2],
    cutoff: 1100,
    resonance: 10,
    delayTime: 0.33,
    decay: 0.18,
  },
  {
    id: 'psy',
    name: 'Psychedelic Portal',
    genre: 'Psy Trance',
    bpm: 138,
    key: 'A Minor Pentatonic',
    description: 'Immersive psychedelic trance loop with highly modulated offbeat basslines, hypnotic squelches, and cosmic echoes.',
    patterns: {
      kick:  [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      hat:   [false, false, true, false, false, false, true, true, false, false, true, false, false, false, true, false],
      clap:  [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      synth: [false, true, true, false, false, true, true, false, false, true, true, false, false, true, true, true],
    },
    synthNotes: [0, 3, 3, 0, 0, 4, 4, 0, 0, 5, 5, 0, 0, 7, 7, 3],
    cutoff: 650,
    resonance: 11,
    delayTime: 0.25,
    decay: 0.12,
  },
  {
    id: 'psytrance',
    name: 'Vini Vici Tribeland',
    genre: 'Psytrance',
    bpm: 142,
    key: 'F# Phrygian',
    description: 'High-octane, triple-gated "KBBB" psytrance rhythm. The bassline gallops perfectly right after each powerful punchy kick.',
    patterns: {
      kick:  [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      hat:   [false, false, true, false, false, true, true, false, false, false, true, false, true, false, true, true],
      clap:  [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      synth: [false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true],
    },
    synthNotes: [0, 0, 0, 0, 0, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 2],
    cutoff: 550,
    resonance: 6,
    delayTime: 0.125,
    decay: 0.14,
  },
  {
    id: 'industrial',
    name: 'Schranz Factory',
    genre: 'Industrial Techno',
    bpm: 140,
    key: 'F# Phrygian',
    description: 'Aggressive, distorted, and heavy warehouse techno with overdriven kicks on almost every step and screeching high-resonance modulations.',
    patterns: {
      kick:  [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
      hat:   [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      clap:  [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true],
      synth: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
    },
    synthNotes: [0, 1, 0, 2, 0, 1, 3, 2, 0, 4, 3, 1, 0, 2, 1, 0],
    cutoff: 1250,
    resonance: 9,
    delayTime: 0.125,
    decay: 0.08,
  },
  {
    id: 'bounce',
    name: 'Melbourne Bounce Club',
    genre: 'Bounce',
    bpm: 128,
    key: 'A Minor Pentatonic',
    description: 'An infectious, upbeat Australian bounce rhythm with a distinct offbeat "woody" bass jump and upbeat energy.',
    patterns: {
      kick:  [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      hat:   [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
      clap:  [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      synth: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true],
    },
    synthNotes: [0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 7, 4],
    cutoff: 720,
    resonance: 7,
    delayTime: 0.25,
    decay: 0.22,
  },
  {
    id: 'hardbounce',
    name: 'Hardstyle Bounce Machine',
    genre: 'Hardbounce',
    bpm: 145,
    key: 'C Minor (Acid)',
    description: 'Extremely energetic hard bounce combining highly resonant acid basslines, 145 BPM tempo, and rapid upbeat synth sweeps.',
    patterns: {
      kick:  [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, true],
      hat:   [false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true],
      clap:  [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      synth: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
    },
    synthNotes: [0, 2, 4, 2, 0, 3, 5, 3, 0, 4, 6, 4, 1, 3, 5, 7],
    cutoff: 1100,
    resonance: 13,
    delayTime: 0.25,
    decay: 0.15,
  },
  {
    id: 'tekk',
    name: 'Hardtekk Overload',
    genre: 'Tekk',
    bpm: 148,
    key: 'C Minor (Acid)',
    description: 'A brutal 148 BPM tekk rhythm featuring heavy pounding distorted low kicks, rapid hats, and metallic screeching industrial synthesizers.',
    patterns: {
      kick:  [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
      hat:   [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, true],
      clap:  [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      synth: [true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true],
    },
    synthNotes: [0, 1, 0, 1, 2, 1, 0, 3, 2, 1, 0, 4, 3, 2, 1, 0],
    cutoff: 1350,
    resonance: 14,
    delayTime: 0.125,
    decay: 0.06,
  }
];
